name: 'CI Jobs'
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install meson
        python -m pip install dbus-python
        pip install -r requirements.txt


        - name: Test 64-bit - Raspberry Pi 02w, 3 and 4
          uses: pguyot/arm-runner-action@HEAD
          with:
            base_image: https://dietpi.com/downloads/images/DietPi_ASUSTB-ARMv7-Bookworm.7z
            cpu: cortex-a53
            commands: |
                echo "ARM TEST - Raspberry Pi 02w, 3 and 4"
                test `uname -m` = 'aarch64'